### ISSUE TITLE
Requesting co maintainer status for colorbox

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/colorbox#11]
hi @biolithic, 
There are a few PRs in the queue that have been marked RTBC and we'd like to merge them and make a new release. Can I please have co-maintainer status to do so?  Thanks!

**Comment by Graham-72** [comment]
@jenlampton are we able to progress this now? Also I am keen to see a swipe capability integrated into Colorbox.

**Comment by jenlampton** [comment]
Yes! :) thanks for the reminder @Graham-72
