### ISSUE TITLE
[META] Review & include changes from recent Drupal releases

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/colorbox#15]
Releases: 
* [x] colorbox 7.x-2.11
* [x] colorbox 7.x-2.12 & 7.x-2.13 #24
* [x] colorbox 7.x-2.14, 7.x-2.15 https://github.com/backdrop-contrib/colorbox/issues/26

**Comment by indigoxela** [comment]
**colorbox 7.x-2.14, 7.x-2.15**

Extra issue created at https://github.com/backdrop-contrib/colorbox/issues/26

**Comment by jenlampton** [comment]
It looks like 2.11 had some bugs that were fixed in 2.12. If we can get those two patches from 2.12 in, we'll be in a (near?) release-ready state.

**Comment by indigoxela** [comment]
> If we can get those two patches from 2.12 in, we'll be in a release-ready state.

I wouldn't bet on it yet. Needs a little more testing, I guess. Views settings behavior seems a little odd to me, but maybe it's just me... (or I'm already too hungry or tired :wink: ).

**Comment by jenlampton** [comment]
I tried to add the changes from 2727829, but the code blcok was missing, so I coped the complete block from the latest version of the Drupal 7 module. I think that last change brings us up to date with D7. If we can test this for a few days and confirm everything still appears not-broken, I'd be interested in making a new release. :)

**Comment by indigoxela** [comment]
> I tried to add the changes from 2727829, but the code blcok was missing,

That's strange, because I also added that. It's here in my local dev fork. It was that commit:
https://github.com/backdrop-contrib/colorbox/pull/25/commits/43f66b4d23257682b422ed7efa77e89e741ed0fb

(Part of Issue #24 catch up with 7.x 2.13)

**Comment by jenlampton** [comment]
Huh, that's weird. I wonder what happened? I'm not seeing that commit in 1.x-2.x.

**Comment by indigoxela** [comment]
>  I'm not seeing that commit in 1.x-2.x.

Ehm... It's there in the commit list and obviously it was merged. I linked to it in my previous comment. :grin: Maybe your local copy lags behind?

**Comment by indigoxela** [comment]
@jenlampton there has been a lot of activity in February and March this year. But the most recent module release is from 2017. Are there any plans yet for a fresh release?

**Comment by jenlampton** [comment]
> Are there any plans yet for a fresh release?

There should be! I'll make one shortly.

**Comment by jenlampton** [comment]
Not as "shortly" as I would have liked, but the release is out: https://github.com/backdrop-contrib/colorbox/releases/tag/1.x-2.15.0
