### ISSUE TITLE
Colorbox styles Example 1-5 do not work

### ISSUE THREAD

**Issue by korontari** [backdrop-contrib/colorbox#18]
When applying Colorbox styles Example 1 - 5 in /configuration/media/colorbox, they appear as if None was selected. Other styles  (Default, Plain and S.Syndrome) work fine.

**Comment by laryn** [comment]
I'm also seeing this in logs occasionally now:

`Notice: Undefined variable: library_colorbox in colorbox_admin_settings() (line 85 of /app/modules/colorbox/colorbox.admin.inc).`

**Comment by bugfolder** [comment]
Just encountered this. Added a PR that fixes the warning.

**Comment by olafgrabienski** [comment]
Thanks @bugfolder! I've finally tested the PR at one of my sites, and the warnings are gone. The Examples 1-5 still don't work. Are you planning to fix those too?

**Comment by bugfolder** [comment]
They're fixed in the updated PR.
