### ISSUE TITLE
Config not imported correctly after initial install

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/colorbox#19]
I just installed this on a site and configured an image field display to use it -- the options showed up for configuration of the field display, but Colorbox was not implemented. I went to look at the settings and realized everything was blank. After configuring and saving, it worked.

Ideally, the config should get imported with sensible defaults that work out of the box.

**Comment by jenlampton** [comment]
It looks like there is now a default config file, with sensible options. I just tested the image formatter "Colorbox" with the default colorbox settings provided, and it appears to be working now. I expect this was fixed in a previous release, but please re-open if you run into the problem again.
