### ISSUE TITLE
Problem with 2.10 update and Views Load More pager module? - evaluate

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/colorbox#23]
Just a quick issue, so we don't forget it...

This is a change I skipped in #21, because it looks too weird for a "blind merge" and it's not completely clear, if the Backdrop version is affected anyway.

This is the Drupal issue: https://www.drupal.org/project/colorbox/issues/2613200

**Comment by jenlampton** [comment]
I've merged in this feature as part of the 2.16.0 release. I also don't know if the problem affects Backdrop, but I merged it in an attempt to keep the code similar to the 7.x version. (and before I'd seen this issue in the queue...)
