### ISSUE TITLE
Caption printing on multiple fields?

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/colorbox#29]
I cannot find a way to print the caption on a multiple image field. I just have an image field configured to be unlimited and using colorbox as display. None of the colorbox caption options works. The caption (either title or alt) is not shown when viewing the image on the colorbox. Am I missing something? Is this a bug?

**Comment by indigoxela** [comment]
@robertgarrigos are you using the "latest" stable version (1.x-2.10.0 from 2017)? Then it might be worth trying out the current dev version.

A lot of work happened earlier this year, but there's no new stable release yet. But there should be soon(ish), I hope.

**Comment by robertgarrigos** [comment]
Thanks @indigoxela I was using the stable version, indeed. Installed the dev version with same results, although there are some differences with the stable. Now I can see a  new "data-cbox-img-attrs" attribute in the image link. However, there is no caption. You can check in this page: https://velesivents.cat/posts/a-punt-per-la-primera-temporada. Every image in the gallery has title and alt field, but colorbox doesn't show the caption.

**Comment by robertgarrigos** [comment]
Found the problem. Is not colorbox's but [Beauty tips](https://github.com/backdrop-contrib/beautytips)' fault. Disabling it allows the colorbox caption to appear again :-)
