### ISSUE TITLE
Clean up `Drupal.` in js file

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/colorbox#31]
It looks like a recent merge of updates from the Drupal side leaked in some `Drupal.`'s in the js file.

**Comment by laryn** [comment]
Also a few `drupal_`'s in the api file.

**Comment by laryn** [comment]
I can submit a PR unless it's easier for you to do it since you seem to be at work at this moment...

**Comment by laryn** [comment]
@jenlampton ☝️

**Comment by jenlampton** [comment]
Thanks @laryn, I meant to do a check for Drupals before I released. Obviously I forgot! PR merged.
