### ISSUE TITLE
Is IMAGE_DERIVATIVE_TOKEN relevant in Backdrop?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/colorbox#32]
My memory is that Backdrop solved this problem differently than Drupal did, so this section may not be relevant:

https://github.com/backdrop-contrib/colorbox/blob/1.x-2.x/colorbox.theme.inc#L245-L249

**Comment by laryn** [comment]
If I'm right, here's a PR to remove that chunk of code.

**Comment by jenlampton** [comment]
Yes, this function was deprecated in 1.0: https://docs.backdropcms.org/api/backdrop/core%21modules%21image%21image.module/function/image_style_path_token/1

PR merged. Thank you!
