### ISSUE TITLE
Colorbox is unable to locate colorbox-insert-image.tpl.php

### ISSUE THREAD

**Issue by jromine** [backdrop-contrib/colorbox#37]
Colorbox module with Insert module is unable to locate its colorbox-insert-image.tpl.php template file. 

### How to reproduce:

1. Enable colorbox module and insert module on an image field for a content type.
2. Visit Content > Add Content > Your content type
3. Click browse and upload an image to the image field
4. This warning is logged/displayed (and the insert button doesn't work for colorbox options):

`Warning: include(): Failed opening '/home/sites/backdrop.eng.uci.edu/modules/colorbox/colorbox-insert-image.tpl.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in include() (line 1541 of /home/sites/backdrop.eng.uci.edu/core/includes/theme.inc).`

### Fix

Move the colorbox-insert-image.tpl.php template file to the module top-level folder and remove the empty tempates/ subdirectory.

Alternatively, move both files into the templates/ subdirectory, and update colorbox_theme() function to include a key:
`'path' = backdrop_get_path('module', 'colorbox') . '/templates'`
in all the theme function definitions. See core/modules/views/views.module for an example.

**Comment by jenlampton** [comment]
A fix for this will be included in the next version. For reference, I added a 'template' key in `hook_theme()` that pointed to  the location of the template.
