### ISSUE TITLE
Illegal string offset 'version'

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/colorbox#42]
Last update of colorbox triggers a new error ```Illegal string offset 'version' a backdrop_get_library() (línia 5453 de /home/robert/nautica/web/core/includes/common.inc)```

Deactivating it removes the error.

**Comment by olafgrabienski** [comment]
Confirmed. Tested on a vanilla Backdrop demo site with only Colorbox 1.x-2.17.0 enabled. Additionally to the error, I see two notices in DBlog after visiting `admin/config/media/colorbox` - **edit:** or even any other page.

- Notice: Undefined variable: library_colorbox in colorbox_admin_settings() (line 81 of /var/lib/tugboat/backdrop/modules/colorbox/colorbox.admin.inc).
- Notice: Trying to access array offset on value of type null in colorbox_admin_settings() (line 81 of /var/lib/tugboat/backdrop/modules/colorbox/colorbox.admin.inc).

**Comment by laryn** [comment]
I can confirm but haven't been able to figure out why.

**Comment by laryn** [comment]
Here's a strange error I see periodically now, too:

> Warning: file_get_contents(2odules/colorbox/libraries/DOMPurify/dist/purify.min.js): failed to open stream: No such file or directory in backdrop_build_js_cache() (line 5644 of /app/core/includes/common.inc).

**Comment by laryn** [comment]
I should note, I think the path to `purify.min.js` is incorrect (I've added the `dist/` in the path above).

**Comment by echozone** [comment]
Illegal string offset 'version' in backdrop_get_library() (line 5453 of /core/includes/common.inc)

Until a real fix, is there a harmless edit just to get rid of this error, it's obtrusive + making the logs unusable.

**Comment by jenlampton** [comment]
I'm going to make a new release shortly containing the fix.

**Comment by laryn** [comment]
@jenlampton Thanks for this! I spot-checked (haven't tested on a live site) but I think the path to `purify.js` and `purify.min.js` is still incorrect and needs the `dist/` added. (OR the DOMPurify library can be reduced to just the contents of the `dist` folder in the `libraries/DOMPurify` folder directly)

**Comment by olafgrabienski** [comment]
@laryn I've just updated a live site to use Colorbox 1.x-2.17.1. At first sight, I don't see any issues on that site. If there is anything to test, let me know.

**Comment by laryn** [comment]
@olafgrabienski @jenlampton Looking back at my comments, I think it relates to the libraries declarations for DOMPurify. [Look at the directory structure to the location of the JS in the declaration](https://github.com/backdrop-contrib/colorbox/blob/1.x-2.x/colorbox.module#L114):

```
$colorbox_path . '/libraries/DOMPurify/purify.min.js' => array(),
```

Compare to the actual directory structure of the DOMPurify library as it is bundled:
![image](https://user-images.githubusercontent.com/871421/213944860-6543ec72-3735-41c0-b67a-a78e68a56f99.png)

It looks like the `dist` directory is missing in the declaration, isn't it?

**Comment by olafgrabienski** [comment]
> It looks like the `dist` directory is missing in the declaration, isn't it?

I see, that's right! If I don't miss anything, `dist/` has to be added in two lines (114 and 122). @jenlampton Can you add that change?

**Comment by nattywebdev** [comment]
I am seeing [this issue](https://github.com/backdrop-contrib/colorbox/issues/42#issuecomment-1399632258) too - was about to make a PR but seems it is in hand... or is it?
@olafgrabienski @laryn @jenlampton

**Comment by bugfolder** [comment]
Agreed that the `dist/` is needed (and still missing). PR filed.

**Comment by olafgrabienski** [comment]
Thanks @bugfolder! Looks good to me.
