### ISSUE TITLE
 Notice: Undefined variable: library_colorbox in colorbox_admin_settings() etc

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/colorbox#44]
After installing and upon visiting Configuration > Media > Colorbox I get:

Error message
Notice: Undefined variable: library_colorbox in colorbox_admin_settings() (line 81 of /Users/alejandrocremaschi/Sites/localhost/bd120/modules/colorbox/colorbox.admin.inc).
Notice: Trying to access array offset on value of type null in colorbox_admin_settings() (line 81 of /Users/alejandrocremaschi/Sites/localhost/bd120/modules/colorbox/colorbox.admin.inc).
Notice: Undefined variable: library_colorbox in colorbox_admin_settings() (line 82 of /Users/alejandrocremaschi/Sites/localhost/bd120/modules/colorbox/colorbox.admin.inc).
Notice: Trying to access array offset on value of type null in colorbox_admin_settings() (line 82 of /Users/alejandrocremaschi/Sites/localhost/bd120/modules/colorbox/colorbox.admin.inc).
Notice: Undefined variable: library_colorbox in colorbox_admin_settings() (line 83 of /Users/alejandrocremaschi/Sites/localhost/bd120/modules/colorbox/colorbox.admin.inc).
Notice: Trying to access array offset on value of type null in colorbox_admin_settings() (line 83 of /Users/alejandrocremaschi/Sites/localhost/bd120/modules/colorbox/colorbox.admin.inc).
Notice: Undefined variable: library_colorbox in colorbox_admin_settings() (line 84 of /Users/alejandrocremaschi/Sites/localhost/bd120/modules/colorbox/colorbox.admin.inc).
Notice: Trying to access array offset on value of type null in colorbox_admin_settings() (line 84 of /Users/alejandrocremaschi/Sites/localhost/bd120/modules/colorbox/colorbox.admin.inc).
Notice: Undefined variable: library_colorbox in colorbox_admin_settings() (line 85 of /Users/alejandrocremaschi/Sites/localhost/bd120/modules/colorbox/colorbox.admin.inc).
Notice: Trying to access array offset on value of type null in colorbox_admin_settings() (line 85 of /Users/alejandrocremaschi/Sites/localhost/bd120/modules/colorbox/colorbox.admin.inc).

**Comment by olafgrabienski** [comment]
Confirmed! (Tested on a fresh Backdrop demo site.)

**Comment by argiepiano** [comment]
This can be fixed by switching all occorrences of `$library_colorbox['library path']` to `$colorbox_path`.

BUT, not all the options to select the Colorbox Style will work: none of the examples (e.g. `Example 1` etc) are provided anywhere in the Backdrop version of the `colorbox` module.

**Comment by nattywebdev** [comment]
I am seeing this error too. Is there any fix available?

**Comment by argiepiano** [comment]
#43 should fix this. It looks like this is a duplicate of #18

**Comment by olafgrabienski** [comment]
Yep, I've tested the PR for issue #18, and it fixes the errors.
