### ISSUE TITLE
Module still includes a check for the token module.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/colorbox#6]
At [colorbox.module line 390](https://github.com/backdrop-contrib/colorbox/blob/1.x-1.x/colorbox.module#L390) there is a check that at [line 409](https://github.com/backdrop-contrib/colorbox/blob/1.x-1.x/colorbox.module#L409) produces a warning in Backdrop.

**Comment by klonos** [comment]
Token is now part of core and always enabled + hidden I think we can safely remove that check.

**Comment by laryn** [comment]
There's a section related to this that can still be cut out:

https://github.com/backdrop-contrib/colorbox/blob/1.x-2.x/colorbox.module#L402-L413

**Comment by laryn** [comment]
Sorry, I had some unrelated changes that kept getting included in there but have a clean PR on this one now.

**Comment by jenlampton** [comment]
Thanks @laryn, PR merged!
